CREATE TABLE IF NOT EXISTS issues (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  -- IssueNumber INTEGER NOT NULL UNIQUE,   this line may be used if you want to have a separate auto-incrementing issue number
  -- Beads use hash ID here to solve Race Condition when multiple issues are created simultaneously. 
  -- The hash ID is generated by the application and is unique.
  Title TEXT NOT NULL,
  Description TEXT,
  -- CHECK constraints enforce allowed values for Status, Priority, and IssueType
  Status TEXT DEFAULT 'open' CHECK (Status IN ('open', 'in_progress', 'closed')),
  -- P0 = blocker, P1 = high, P2 = medium, P3 = low.
  -- Default p3 forces creators to actively bump priority for anything urgent.
  Priority TEXT DEFAULT 'p3' CHECK (Priority IN ('p0', 'p1', 'p2', 'p3')),
  IssueType TEXT DEFAULT 'task' CHECK (IssueType IN ('task', 'bug')),
  Assignee TEXT,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  CreatedBy TEXT NOT NULL,
  UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  UpdatedBy TEXT NOT NULL
);

-- Speed up MAX(IssueNumber) and lookup-by-number queries
-- CREATE INDEX IF NOT EXISTS idx_issues_issue_number ON issues(IssueNumber);  